In [ ]:
!pip install requests

Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (2.32.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests) (2026.5.20)

In [31]:
import requests
import pandas as pd

def air_quality_data(lat, lon,start_date,end_date):

    url = (
        "https://air-quality-api.open-meteo.com/v1/air-quality"
        f"?latitude={lat}"
        f"&longitude={lon}"
        f"&start_date={start_date}"
        f"&end_date={end_date}"
        "&hourly=pm2_5,pm10,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,european_aqi"
    )

    response = requests.get(url)

    if response.status_code != 200:
        print("API failed:", response.status_code)
        return None

    data = response.json()

    if "hourly" not in data:
        print("No hourly key found")
        return None

    return data

In [32]:
data=air_quality_data(
    lat=33.6844,
    lon=73.0479,
    start_date="2023-01-01",
    end_date="2026-06-21"
)

In [33]:
print(type(data))
print(data
      )

<class 'dict'>

In [34]:
df = pd.DataFrame(data["hourly"])
df.head()

,time,pm2_5,pm10,carbon_monoxide,nitrogen_dioxide,sulphur_dioxide,ozone,european_aqi
0,2023-01-01T00:00,32.6,49.2,649.0,8.7,5.1,81.0,77
1,2023-01-01T01:00,34.7,52.0,931.0,22.5,5.5,65.0,77
2,2023-01-01T02:00,38.6,57.7,1329.0,42.1,6.0,42.0,76
3,2023-01-01T03:00,45.3,67.1,1678.0,59.8,7.4,27.0,76
4,2023-01-01T04:00,54.4,79.6,1636.0,58.8,9.1,41.0,76

In [36]:
df.shape

(30432, 8)

In [39]:
print("Null values in the data")
df.isnull().sum()/len(df.shape)

Null values in the data

time                0.0
pm2_5               0.0
pm10                0.0
carbon_monoxide     0.0
nitrogen_dioxide    0.0
sulphur_dioxide     0.0
ozone               0.0
european_aqi        0.0
dtype: float64

In [48]:
def get_weather_data(lat, lon, start_date, end_date):

    url = (
        "https://archive-api.open-meteo.com/v1/era5"
        f"?latitude={lat}"
        f"&longitude={lon}"
        f"&start_date={start_date}"
        f"&end_date={end_date}"
        "&hourly=temperature_2m,relative_humidity_2m,"
        "wind_speed_10m,pressure_msl,precipitation"
    )

    r = requests.get(url)
    if r.status_code!=200:
        print("API failed:",r.status_code)
        return None

    data = r.json()


    if "hourly" not in data:
        print("No hourly key found")
        return None
    return data

In [49]:
data001= get_weather_data(
    lat=33.6844,
    lon=73.0479,
    start_date="2023-01-01",
    end_date="2026-06-21"
)

In [51]:
print(type(data001))
print(data001)

<class 'dict'>

In [52]:
weather_data_df = pd.DataFrame(data001["hourly"])
weather_data_df.head()

,time,temperature_2m,relative_humidity_2m,wind_speed_10m,pressure_msl,precipitation
0,2023-01-01T00:00,4.9,79,6.3,1019.4,0.0
1,2023-01-01T01:00,5.1,77,5.9,1019.5,0.0
2,2023-01-01T02:00,6.9,68,2.5,1020.2,0.0
3,2023-01-01T03:00,5.7,79,3.8,1020.9,0.0
4,2023-01-01T04:00,9.6,65,3.8,1021.3,0.0

In [53]:
weather_data_df.shape

(30432, 6)

In [54]:
final_df = df.merge(weather_data_df,on="time",how="inner")

In [55]:
final_df.shape

(30432, 13)

In [57]:
final_df.isnull().sum()/df.shape[0]

time                    0.0
pm2_5                   0.0
pm10                    0.0
carbon_monoxide         0.0
nitrogen_dioxide        0.0
sulphur_dioxide         0.0
ozone                   0.0
european_aqi            0.0
temperature_2m          0.0
relative_humidity_2m    0.0
wind_speed_10m          0.0
pressure_msl            0.0
precipitation           0.0
dtype: float64

In [58]:
final_df['time'].head(5)

0    2023-01-01T00:00
1    2023-01-01T01:00
2    2023-01-01T02:00
3    2023-01-01T03:00
4    2023-01-01T04:00
Name: time, dtype: object

In [61]:
final_df["time"] = pd.to_datetime(final_df["time"])

In [62]:
final_df['time'].head(5)

0   2023-01-01 00:00:00
1   2023-01-01 01:00:00
2   2023-01-01 02:00:00
3   2023-01-01 03:00:00
4   2023-01-01 04:00:00
Name: time, dtype: datetime64[ns]

In [64]:
final_df = final_df.sort_values("time")

# time — exact timestamp of observation (hourly record)
# pm2_5 — very fine harmful particles that can directly enter the lungs
# pm10 — larger dust particles that indicate overall air pollution level
# carbon_monoxide — toxic gas mainly produced by vehicles and fuel burning
# nitrogen_dioxide — harmful gas from traffic and industrial emissions
# sulphur_dioxide — pollutant gas released from factories and burning fossil fuels
# ozone — harmful gas formed by chemical reactions between sunlight and pollutants
# european_aqi — overall air quality index representing pollution severity
# temperature_2m — air temperature measured near ground level
# relative_humidity_2m — percentage of moisture present in the air
# wind_speed_10m — speed of wind that helps disperse pollutants
# pressure_msl — atmospheric pressure indicating weather stability conditions
# precipitation — amount of rainfall that helps clean pollutants from the air

In [67]:
final_df.columns

Index(['time', 'pm2_5', 'pm10', 'carbon_monoxide', 'nitrogen_dioxide',
       'sulphur_dioxide', 'ozone', 'european_aqi', 'temperature_2m',
       'relative_humidity_2m', 'wind_speed_10m', 'pressure_msl',
       'precipitation'],
      dtype='object')

In [69]:
final_df.to_csv("final_df.csv",index=False)